# Generated by Django 2.2.1 on 2020-08-13 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_registromodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromodel',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 8, 13, 16, 51, 12, 809106), verbose_name='Data'),
        ),
    ]
